### ISSUE TITLE
a.show() seems to have no effect

### ISSUE THREAD

**Issue by jrefano** [hydra-synth/hydra#190] opened 2022-04-06 16:22 UTC
should this be literally showing a waveform somewhere similarly to how you see on https://meyda.js.org?  i can get my code to respond to sound input but this implies there's a way to see the frequencies?  sorry if i am misunderstanding. thanks

**Comment by ritchse** [comment] 2022-04-06 18:54
no, it usually shows the different bins. there should be a small canvas at the lower right section of the screen showing them. however there are many changes being done to the editor now (most specifically, changing to using the choo framework) and that small canvas just hasn't been ported yet, this will be fixed soon enough

**Comment by ojack** [comment] 2022-04-07 12:37
caused by https://github.com/hydra-synth/hydra-synth/issues/114

**Closed** 2022-04-11 17:15 UTC
